#!/usr/bin/sh
#
# Patch acd(1) pass description file to enable runtime debug support (grind)
# (C) 2005 Michael Kennett

action=
c=/usr/src/commands/i386

if [ ! -d $c -o ! -f $c/Makefile ]
then
    echo "*** ERROR: '$c/Makefile' does not exist"
    exit 1
fi

# Patch makefile to increase memory allocated to acd
stack=`grep "install -S" $c/Makefile | awk '{print $3}' | sed 's/kw//'`
if [ $stack -ne 30 ]
then
    action=done
    ed - $c/Makefile << EOF
/install -S ${stack}kw/s/${stack}/30/
w
q
EOF
fi

# Patch existing acd(1) binary
chmod u+w /usr/bin/acd
mem=`chmem +0 /usr/bin/acd | sed -e 's/.*to \([0-9]*\).*/\1/'`

if [ $mem -lt 110592 ]
then
    action=done
    echo "*** Increasing memory allocated to /usr/bin/acd"
    chmem =110592 /usr/bin/acd
fi
chmod u-w /usr/bin/acd

d=/usr/lib/descr
if [ ! -f $d ]
then
    echo "*** ERROR: '$d' does not exist"
    exit 1
fi

if grep DEBUG $d > /dev/null
then
    : already patched
else
    action=done
    echo Patching $d to support grind...
    ed - $d > /dev/null << EOF
/ACK_CV/c
ACK_CV =	\$A/cv -x -m\$ARCH
.
/arg -g/
/ACK_CG/c
	ACK_BEM = \$ACK_BEM -t
	DEBUG = true

arg -G\$symfile
arg -G \$symfile
	SYMFILE = \$symfile
.
/	libs =/i
	ifdef DEBUG
		if \$MODEL = ()
			libdb = \$A/\$ARCH/libgrindc.a
		if \$MODEL = (-sep)
			libdb = \$A/\$ARCH/libgrinds.a
.
/libs =/s/libd/libdb \$libd/
/OUT =/a
	ifdef DEBUG
		ifndef SYMFILE
			SYMFILE = \$OUT.dbg
		ACK_CV = \$ACK_CV -g \$SYMFILE
.
/ACK_CV/s/-x -m\$ARCH//
w
q
EOF
fi

if [ x$action = xdone ]
then
    echo "*** fix-grind-support : patch succesfully applied"
else
    echo "*** fix-grind-support : nothing done (patch previously applied)"
fi

exit 0

