#!/usr/bin/sh
#
# Patch acd(1) pass description file to enable extra ACK languages
# (C) 2005 Michael Kennett

action=
c=/usr/src/commands/i386

if [ ! -d $c -o ! -f $c/Makefile ]
then
    echo "*** ERROR: '$c/Makefile' does not exist"
    exit 1
fi

# Patch makefile to increase memory allocated to acd
stack=`grep "install -S" $c/Makefile | awk '{print $3}' | sed 's/kw//'`
if [ $stack -ne 30 ]
then
    action=done
    ed - $c/Makefile << EOF
/install -S ${stack}kw/s/${stack}/30/
w
q
EOF
fi

# Patch existing acd(1) binary
chmod u+w /usr/bin/acd
mem=`chmem +0 /usr/bin/acd | sed -e 's/.*to \([0-9]*\).*/\1/'`

if [ $mem -lt 110592 ]
then
    action=done
    echo "*** Increasing memory allocated to /usr/bin/acd"
    chmem =110592 /usr/bin/acd
fi
chmod u-w /usr/bin/acd

d=/usr/lib/descr
if [ ! -f $d ]
then
    echo "*** ERROR: '$d' does not exist"
    exit 1
fi

if grep ACK_OCCAM $d > /dev/null
then
    : already patched
else
    action=done
    echo Patching $d to support occam...
    ed - $d > /dev/null << EOF
/ACK_PC/i
ACK_OCCAM =	\$A/em_occam -Vw\${W}l4p${P}
.
/arg -.p/i
arg -.ocm
if \$PROGRAM = occam
	ifndef RTSO
		RTSO = -.ocm
	LIBS = \$LIBS + -.ocm

.
/arg -n/
/ACK_PC/i
	ACK_OCCAM = \$ACK_OCCAM -L
.
/arg -Wack-R\$pass-\$flag/
/if \$pass = pc/i
	if \$pass = occam
		ACK_OCCAM = \$ACK_OCCAM -\$flag
.
/# Compile Pascal source to EM-code./i
# Compile Occam source to EM-code.
transform .ocm .k
	ifhash \$*
		apply .c .i
	\$ACK_OCCAM < \$* > \$>
	ifndef RTSO
		RTSO = -.ocm
	LIBS = \$LIBS + -.ocm

.
/combine (.o .a) .out/
/if \$RTSO = -.p/i
	if \$RTSO = -.ocm
		rtso = \$A/\$ARCH/crtso.o
.
/if (-.p - \$LIBS)/i
	if (-.ocm - \$LIBS) = ()
		libocm = \$A/\$ARCH/libocm.a
		libc = \$A/\$ARCH/libc.a
.
/libs =/s/libp/libocm \$libp/
w
q
EOF
fi

if [ ! -f /usr/bin/occam ]
then
    action=done
    ln /usr/bin/acd /usr/bin/occam
fi

if [ x$action = xdone ]
then
    echo "*** fix-occam-support : patch succesfully applied"
else
    echo "*** fix-occam-support : nothing done (patch previously applied)"
fi

exit 0

