# Generated by h2py from /usr/include/fcntl.h

# Included from sys/types.h

# Included from ansi.h
_ANSI = 31459
_ANSI = 31459
def _ARGS(params): return params

def _ARGS(params): return ()

_SIZET = int
_POSIX_SOURCE = 1
F_DUPFD = 0
F_GETFD = 1
F_SETFD = 2
F_GETFL = 3
F_SETFL = 4
F_GETLK = 5
F_SETLK = 6
F_SETLKW = 7
FD_CLOEXEC = 1
F_RDLCK = 1
F_WRLCK = 2
F_UNLCK = 3
O_CREAT = 00100
O_EXCL = 00200
O_NOCTTY = 00400
O_TRUNC = 01000
O_APPEND = 02000
O_NONBLOCK = 04000
O_RDONLY = 0
O_WRONLY = 1
O_RDWR = 2
O_ACCMODE = 03
